# Generated by Django 4.0.2 on 2022-03-12 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volum', models.FloatField(max_length=5)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Inválido', 'Inválido'), ('Andamento', 'Andamento'), ('Pronto', 'Pronto')], default='Andamento', max_length=9)),
                ('exam_type', models.CharField(choices=[('Hemograma', 'Hemograma'), ('Colesterol e Triglicerídeos', 'Colesterol e Triglicerídeos'), ('Mamografia', 'Mamografia'), ('Ressonância Magnética', 'Ressonância Magnética'), ('Tomografia', 'Tomografia'), ('Ultra-sonografia', 'Ultra-sonografia'), ('Biópsia', 'Biópsia'), ('Colonoscopia', 'Colonoscopia'), ('Raio X', 'Raio X'), ('Laringoscopia', 'Laringoscopia'), ('Cateterismo', 'Cateterismo'), ('Urografia', 'Urografia'), ('Teste do Pezinho', 'Teste do Pezinho'), ('Endoscopia', 'Endoscopia'), ('Eletroencefalografia', 'Eletroencefalografia'), ('Exame de Fezes', 'Exame de Fezes'), ('Diagnostico Pré-Natal', 'Diagnostico Pré-Natal')], max_length=30)),
                ('exam_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_records', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
