# Generated by Django 4.0.3 on 2022-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidade', '0005_alter_exame_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='state',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Pronto', 'Pronto')], default='Em Andamento', max_length=12),
        ),
    ]
