# Generated by Django 4.0.2 on 2022-04-04 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidade', '0006_alter_exame_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancosanguineo',
            name='danation_hour',
            field=models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='consult_date',
            field=models.CharField(choices=[('04 DE ABRIL', '04 DE ABRIL'), ('05 DE ABRIL', '05 DE ABRIL'), ('06 DE ABRIL', '06 DE ABRIL'), ('07 DE ABRIL', '07 DE ABRIL'), ('08 DE ABRIL', '08 DE ABRIL')], default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='consult_hour',
            field=models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='exam_hour',
            field=models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bancosanguineo',
            name='donation_date',
            field=models.CharField(choices=[('04 DE ABRIL', '04 DE ABRIL'), ('05 DE ABRIL', '05 DE ABRIL'), ('06 DE ABRIL', '06 DE ABRIL'), ('07 DE ABRIL', '07 DE ABRIL'), ('08 DE ABRIL', '08 DE ABRIL')], max_length=12),
        ),
        migrations.AlterField(
            model_name='exame',
            name='exam_date',
            field=models.CharField(choices=[('04 DE ABRIL', '04 DE ABRIL'), ('05 DE ABRIL', '05 DE ABRIL'), ('06 DE ABRIL', '06 DE ABRIL'), ('07 DE ABRIL', '07 DE ABRIL'), ('08 DE ABRIL', '08 DE ABRIL')], max_length=12),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='date',
            field=models.CharField(choices=[('04 DE ABRIL', '04 DE ABRIL'), ('05 DE ABRIL', '05 DE ABRIL'), ('06 DE ABRIL', '06 DE ABRIL'), ('07 DE ABRIL', '07 DE ABRIL'), ('08 DE ABRIL', '08 DE ABRIL')], max_length=12),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='date',
            field=models.CharField(choices=[('04 DE ABRIL', '04 DE ABRIL'), ('05 DE ABRIL', '05 DE ABRIL'), ('06 DE ABRIL', '06 DE ABRIL'), ('07 DE ABRIL', '07 DE ABRIL'), ('08 DE ABRIL', '08 DE ABRIL')], max_length=12),
        ),
    ]
