# Generated by Django 4.0.2 on 2022-04-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidade', '0007_bancosanguineo_danation_hour_consulta_consult_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancosanguineo',
            old_name='danation_hour',
            new_name='donation_hour',
        ),
    ]
