# Generated by Django 4.0.3 on 2022-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_delete_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='specialty',
            field=models.CharField(max_length=30),
        ),
    ]
