# Generated by Django 4.0.3 on 2022-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_medico_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='uf',
            field=models.CharField(default='PE', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=10),
        ),
    ]
